Feat/recommendation detail
hmif-itb/hmif-app-fe pull request #62
Opened 2024-11-27 17:01 UTC by WwzFwz

2024-11-28 16:39 UTC, RMA1403 requested changes

2024-11-28 16:39 UTC, RMA1403 commented on package.json
> +  "packageManager": "pnpm@9.12.3+sha512.cce0f9de9c5a7c95bef944169cc5dfe8741abfb145078c0d508b868056848a87c81e626246cb60967cbd7fd29a6c062ef73ff840d96b3c86c40ac92cf4a813ee"
Ini apa ya? kalo ga terlalu penting bisa direvert aja changes yang ini

2024-11-28 16:41 UTC, RMA1403 commented
Title PR nya diganti formatnya jadi "[judul task di Clickup] [id task di Clickup]" yak

2024-11-30 09:17 UTC, WwzFwz commented on package.json
> +  "packageManager": "pnpm@9.12.3+sha512.cce0f9de9c5a7c95bef944169cc5dfe8741abfb145078c0d508b868056848a87c81e626246cb60967cbd7fd29a6c062ef73ff840d96b3c86c40ac92cf4a813ee"
baik kak

2024-12-01 00:50 UTC, RMA1403 approved these changes

2024-12-01 00:50 UTC, merged